ARG GOLANG_VERSION=1.19-alpine

FROM golang:${GOLANG_VERSION} AS build
WORKDIR /build
COPY . .

RUN go mod vendor

WORKDIR /build/cmd
RUN go build  -o /bin/client -mod=vendor

FROM alpine:latest AS dev

COPY --from=build /bin/client /bin/client

WORKDIR /bin
ENTRYPOINT ["/bin/client"]
